server:
  servlet:
    context-path: /
spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: gerenciamento
  datasource:
    url: jdbc:mysql://localhost:3306/pgerenciador
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gerenciamentodb
app:
  general:
    pageSize: 3
  security:
    masterApiKey: O8OZCaaCd5CDFiq2k31RrXrs1c9fRM86
    expirationDays: 2

