server:
  servlet:
    context-path: /
spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: gerenciamento
  datasource:
    url: jdbc:mysql://localhost:3306/pgerenciador
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
app:
  pageSize: 3
